#!/usr/bin/env python3

from dataclasses import dataclass
import logging.config
import subprocess
import os
import sys
import shutil
from pathlib import Path
import logging

ENV_WORK_DIR = "WORK_DIR"
ENV_OUT_DIR = "OUT_DIR"
ENV_LEAF_WORKSPACE = "LEAF_WORKSPACE"

ENV_LOG_LEVEL = "LEAFS_LOG_LEVEL"
ENV_ADD_LEAF_AS_DEP = "LEAFS_ADD_LEAF_AS_DEP"
ENV_TOOLCHAIN_MARKER = "LEAFS_TOOLCHAIN_MARKER_FILE"

ENV_LEAFC = "LEAFC"
ENV_LEAFC_BUILDING_CORE = "LEAFC_BUILDING_CORE"
ENV_CARGO = "CARGO"
ENV_RUSTC = "RUSTC"

BUILD_TARGET = "x86_64-unknown-linux-gnu"
# debug or release
BUILD_PROFILE = "release"

SHIM_MODULE_NAME = "leafrtsh"

OPTS_BUILD_STD = [
    "-Zbuild-std=core,std,panic_unwind,panic_abort,test",
    f"--target={BUILD_TARGET}",
]


@dataclass
class Paths:
    work: Path
    out: Path
    res: Path
    leaf_workspace: Path


def run_command(**kwargs):
    logging.debug(
        "Running: %s %s",
        " ".join(str(arg) for arg in kwargs["args"]),
        "in " + str(kwargs.get("cwd", Path.cwd())),
    )
    if not kwargs.get("capture_output", False):
        kwargs.setdefault("stdout", subprocess.DEVNULL)
        kwargs.setdefault("stderr", subprocess.DEVNULL)

    return subprocess.run(**kwargs)


def ensure_env_dir(var_name: str, default) -> Path:
    path = Path(os.environ.get(var_name, default=default))
    assert not path.exists() or path.is_dir()
    path.mkdir(parents=True, exist_ok=True)
    return path


def add_empty_file(folder: Path, name: str):
    file = folder.joinpath(name)
    file.touch()
    return file


def find_leaf_workspace_dir() -> Path:
    workspace_dir = os.environ.get(ENV_LEAF_WORKSPACE)
    if not workspace_dir:
        # Traverse up the parent directories to find the workspace
        current_dir = Path(__file__).parent
        while not current_dir.joinpath("Cargo.toml").exists():
            parent = current_dir.parent
            if parent == current_dir:
                raise FileNotFoundError("Leaf workspace not found")
            current_dir = parent
        workspace_dir = current_dir
    else:
        workspace_dir = Path(workspace_dir)

    # Check some assumed structure
    assert workspace_dir.joinpath("common").exists()
    assert workspace_dir.joinpath("runtime").exists()

    return workspace_dir


def should_add_leaf_as_dep() -> bool:
    env_val = os.environ.get(ENV_ADD_LEAF_AS_DEP, "true").lower()
    return env_val in [
        "true",
        "1",
        "yes",
        "y",
        "on",
    ]


def get_toolchain_path(cwd, env=None) -> Path:
    try:
        process = run_command(
            args=[
                "cargo",
                "rustc",
                # Cargo tries to build the dependencies, even if we only want to work with rustc.
                # So, we need to make sure that build succeeds.
                *OPTS_BUILD_STD,
                "--",
                "--print=sysroot",
            ],
            cwd=cwd,
            env={**env, ENV_LEAFC_BUILDING_CORE: "true"},
            check=True,
            capture_output=True,
        )
        path = process.stdout.decode("utf-8").strip()
        logging.debug("Toolchain path: %s", path)
        logging.debug("Toolchain path stderr: %s", process.stderr.decode("utf-8"))
        return Path(path)
    except subprocess.CalledProcessError as e:
        logging.error("Failed to get the toolchain path: %s", e.stderr.decode("utf-8"))
        raise


def get_core_src_dir(toolchain_path) -> Path:
    return toolchain_path.joinpath(
        "lib", "rustlib", "src", "rust", "library", "core", "src"
    )


def copy_toolchain(toolchain_path: Path, work_dir: Path) -> Path:
    core_src_dir = get_core_src_dir(toolchain_path)
    assert (
        core_src_dir.exists()
    ), "Core source directory does not exist. Make sure you have added the source component to the toolchain."

    def internal_copy_toolchain(link: bool) -> Path:
        dst_dir = work_dir.joinpath("toolchain")
        if dst_dir.exists():
            shutil.rmtree(dst_dir)

        if link:
            # Symbolically copy the toolchain to the work directory except for the core source
            dst_dir.mkdir(parents=True)
            work_list = [toolchain_path]
            while len(work_list) > 0:
                current = work_list.pop()
                for child in current.iterdir():
                    if core_src_dir.is_relative_to(child):
                        if child == core_src_dir:
                            # Copy the actual core source
                            shutil.copytree(
                                child,
                                dst_dir.joinpath(child.relative_to(toolchain_path)),
                                dirs_exist_ok=True,
                            )
                        else:
                            work_list.append(child)
                    else:
                        # Linking the rest
                        link_path = dst_dir.joinpath(child.relative_to(toolchain_path))
                        link_path.parent.mkdir(parents=True, exist_ok=True)

                        # Binary files must have a real path to give the correct sysroot.
                        # The rest like source files can be symbolically linked.
                        if "src" in str(link_path):
                            link_path.symlink_to(child, target_is_directory=True)
                        elif child.is_dir():
                            shutil.copytree(
                                child,
                                link_path,
                                copy_function=os.link,
                            )
                        else:
                            link_path.hardlink_to(child)
        else:
            shutil.copytree(toolchain_path, dst_dir)

        return dst_dir

    try:
        result = internal_copy_toolchain(link=True)
    except Exception as e:
        logging.debug("Failed to link the toolchain. Copying instead.")
        logging.debug("Error: %s...", str(e)[:200])
        result = internal_copy_toolchain(link=False)

    return result


def add_leaf_to_core(core_src_dir: Path, leaf_workspace_dir: Path, res_dir: Path):
    module_dir = core_src_dir.joinpath("leaf")
    module_dir.mkdir(exist_ok=True)

    def add_common_module(common_src_dir: Path):
        logging.debug("Adding common")
        dst_dir = module_dir.joinpath("common")
        dst_dir.mkdir(exist_ok=True)
        modules = ["ffi", "pri", "types", "utils"]
        for module in modules:
            if common_src_dir.joinpath(f"{module}.rs").exists():
                shutil.copy(common_src_dir.joinpath(f"{module}.rs"), dst_dir)
            else:
                shutil.copytree(
                    common_src_dir.joinpath(module), dst_dir.joinpath(module)
                )
        # Making appropriate mod.rs
        with open(dst_dir.joinpath("mod.rs"), "w") as f:
            f.writelines((f"pub(crate) mod {m};" for m in modules))

    def add_shim_module(shim_src_dir: Path):
        logging.debug("Adding the runtime shim library")
        dst_dir = module_dir.joinpath(SHIM_MODULE_NAME)
        shutil.copytree(shim_src_dir, dst_dir, dirs_exist_ok=True)
        # Rename lib.rs to mod.rs
        shutil.move(dst_dir.joinpath("lib.rs"), dst_dir.joinpath("mod.rs"))

    def apply_patches():
        logging.debug("Applying patches")
        for patch_path in res_dir.joinpath("patches").glob("*.patch"):
            process = run_command(
                args=[
                    "git",
                    "apply",
                    "--verbose",
                    "-C1",
                    "--unsafe-paths",
                    "--directory",
                    core_src_dir,
                    patch_path,
                ],
                cwd=core_src_dir,
                env={
                    "GIT_CEILING_DIRECTORIES": core_src_dir.parent,
                },
                check=True,
                capture_output=True,
            )
            logging.debug("Patch output: %s", process.stdout.decode("utf-8"))
            logging.debug("Patch stderr: %s", process.stderr.decode("utf-8"))

        # Probe patching is effective.
        assert Path(core_src_dir.joinpath("leaf", "mod.rs")).exists()

    logging.info("Adding leaf to the core library source")

    add_common_module(leaf_workspace_dir.joinpath("common", "src"))
    add_shim_module(leaf_workspace_dir.joinpath("runtime", "shim", "src"))
    apply_patches()


def create_dummy_crate(work_dir: Path, res_dir: Path) -> Path:
    template_dir = res_dir.joinpath("crate_template")
    crate_path = work_dir.joinpath("dummy_crate")
    if crate_path.exists():
        shutil.rmtree(crate_path)
    shutil.copytree(template_dir, crate_path)

    return crate_path


def substitute_template(template_path: Path, **substitutions: object):
    from string import Template

    with open(template_path, "r") as f:
        template = Template(f.read())

    with open(template_path.with_suffix(""), "w") as f:
        f.write(template.substitute(**substitutions))


def set_dummy_crate_config_toml(
    dummy_crate_dir: Path,
    add_leaf_as_dep: bool,
    enable_core_build_cfg: bool,
):
    substitute_template(
        dummy_crate_dir.joinpath(".cargo", "config.toml.template"),
        leaf_as_in_core_switch="#" if add_leaf_as_dep else "",
        leaf_as_external_switch="#" if not add_leaf_as_dep else "",
        core_build_cfg_switch="#" if not enable_core_build_cfg else "",
    )


def set_dummy_crate_cargo_toml(
    dummy_crate_dir: Path, add_leaf_as_dep: bool, leaf_workspace_dir: Path
):
    substitute_template(
        dummy_crate_dir.joinpath("Cargo.toml.template"),
        leaf_workspace_dir=leaf_workspace_dir,
        leaf_dep_switch="#" if not add_leaf_as_dep else "",
    )


def get_build_env(toolchain_path: Path):
    # Also check the environment variables set in config.toml
    return {
        **os.environ,
        ENV_RUSTC: os.environ.get(ENV_LEAFC, default="leafc"),
        ENV_LEAFC_BUILDING_CORE: "true",
        "RUSTUP_TOOLCHAIN": str(toolchain_path),
        # "CARGO_LOG": "debug",
    }


def build_crate_with_core(dummy_crate_dir: Path, toolchain_path):
    logging.info("Building the core library through dummy crate")

    output = (
        subprocess.DEVNULL if logging.getLogger().level > logging.DEBUG else sys.stderr
    )
    args = [
        "cargo",
        "build",
        # Causes the core lib to be built as a dependency
        *OPTS_BUILD_STD,
        "--verbose",
        f"--profile={'dev' if BUILD_PROFILE == 'debug' else BUILD_PROFILE}",
        # You can switch to a single thread for easier debugging
        # "-j1",
    ]
    run_command(
        args=args,
        cwd=dummy_crate_dir,
        env=get_build_env(toolchain_path),
        check=True,
        stdout=output,
        stderr=output,
    )

    logging.info("Successfully built the core library.")


def make_toolchain(dummy_crate_dir: Path, out_dir: Path) -> Path:
    logging.info("Making a toolchain from the built libraries")

    deps_dir = dummy_crate_dir.joinpath("target", BUILD_TARGET, BUILD_PROFILE, "deps")
    # As this dummy crate depends only on the core lib, all of the dependencies
    # are part of the sysroot.
    logging.debug("Globbing lib files in %s", deps_dir)
    lib_files = set(deps_dir.glob("lib*.r*")) - set(deps_dir.glob("libdummy*"))
    logging.debug("Found lib files: %s", lib_files)

    toolchain_dir = out_dir.joinpath("toolchain")
    dst_dir = toolchain_dir.joinpath("lib", "rustlib", BUILD_TARGET, "lib")
    dst_dir.mkdir(parents=True, exist_ok=True)
    # Clear the destination directory
    for file in dst_dir.glob("lib*.r*"):
        file.unlink()
    for file in lib_files:
        shutil.copy(file, dst_dir)

    if ENV_TOOLCHAIN_MARKER in os.environ:
        logging.debug("Adding a toolchain marker file")
        add_empty_file(toolchain_dir, os.environ[ENV_TOOLCHAIN_MARKER])

    return toolchain_dir


def main():
    logging.info("Building core lib with leaf")
    logging.info(
        "You can control the log level of this script with the environment variable %s",
        ENV_LOG_LEVEL,
    )
    logging.debug("Environment: %s", os.environ)

    paths = Paths(
        work=ensure_env_dir(ENV_WORK_DIR, default=Path("./work")),
        out=ensure_env_dir(ENV_OUT_DIR, default=Path("./out")),
        res=Path(__file__).parent.joinpath(f"res"),
        leaf_workspace=find_leaf_workspace_dir(),
    )
    logging.debug("Paths: %s", paths.__repr__())

    add_leaf_as_dep = should_add_leaf_as_dep()
    logging.info(
        "Leaf's runtime shim will be %s.",
        "added as a dependency" if add_leaf_as_dep else "added to core library",
    )

    dummy_crate_dir = create_dummy_crate(paths.work, paths.res)
    set_dummy_crate_cargo_toml(dummy_crate_dir, add_leaf_as_dep, paths.leaf_workspace)

    run_command(
        args=["cargo", "--version"], cwd=dummy_crate_dir, env=os.environ, check=True
    )

    orig_toolchain_path = get_toolchain_path(cwd=dummy_crate_dir, env=os.environ)
    logging.debug("Original toolchain path: %s", orig_toolchain_path)

    target_toolchain_path = orig_toolchain_path
    if not add_leaf_as_dep:
        target_toolchain_path = copy_toolchain(
            orig_toolchain_path, paths.work
        ).absolute()
        logging.debug("Copied toolchain path: %s", target_toolchain_path)

    set_dummy_crate_config_toml(
        dummy_crate_dir,
        add_leaf_as_dep,
        enable_core_build_cfg=not add_leaf_as_dep,
    )
    toolchain_path = get_toolchain_path(
        cwd=dummy_crate_dir, env=get_build_env(target_toolchain_path)
    )
    logging.debug("Toolchain path: %s", toolchain_path)
    assert toolchain_path.absolute() == target_toolchain_path.absolute(), (
        toolchain_path,
        target_toolchain_path,
    )

    if not add_leaf_as_dep:
        core_src = get_core_src_dir(toolchain_path)
        logging.debug("Core source dir: %s", core_src)
        add_leaf_to_core(core_src, paths.leaf_workspace, paths.res)

    build_crate_with_core(dummy_crate_dir, toolchain_path)
    out_toolchain_path = make_toolchain(dummy_crate_dir, paths.out)

    print(out_toolchain_path.absolute())


if __name__ == "__main__":
    logging.basicConfig(
        level=os.environ.get(ENV_LOG_LEVEL, default="INFO").upper(),
        format="[%(asctime)s %(levelname)s] %(message)s",
        stream=sys.stderr,
    )
    main()
