#!/bin/sh
# NOTE: be sure to copy this file to `.git/hooks/pre-commit`
changed_files=$(git diff --name-only --cached)
found_changes=false
results=$(rustfmt $changed_files -l)
if [ ! -z "$results" ]; then # check if results isn't empty
    echo -n "file formatted with rustfmt: "
    # making paths relative to the project root
    results=$(echo "$results" | xargs -I {} realpath --relative-to=$(pwd) {})
    echo $results
    found_changes=true
fi

if $found_changes; then
    echo ""
    echo "Please address changes before comitting again"
    exit 1
else
    echo "success"
fi