#!/usr/bin/env python3

import subprocess
import os
from pathlib import Path
import sys
import tempfile


def main():
    script_dir = Path(__file__).resolve().parent
    reachability_path = os.path.join(script_dir, "Reachability")

    temp_dir = (
        Path(tempfile.gettempdir()).joinpath("leaf").joinpath("calc_reachability")
    )
    temp_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(dir=temp_dir) as work_dir:
        work_dir = Path(work_dir)
        with work_dir.joinpath("Edge.facts").open("w") as f:
            f.write(sys.stdin.read())

        subprocess.run([reachability_path], cwd=work_dir, check=True)
        with work_dir.joinpath("Reachable.csv").open("r") as f:
            sys.stdout.write(f.read())


if __name__ == "__main__":
    main()
